import localFont from 'next/font/local';
import './globals.css';
import { AuthProvider } from '@/components/authProvider';
import { ThemeProvider } from '@/components/themeProvider';
import { cn } from '@/lib/utils';
import { Inter as FontSans } from 'next/font/google';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <AuthProvider> {children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
